---
services:
    - name: "NetworkManager"
      mandatory: true
    - name: "sddm"
      mandatory: true
    - name: "bluetooth"
      mandatory: false
    - name: "firewalld"
      mandatory: false
    - name: "fstrim.timer"
      mandatory: false
    - name: "reflector.timer"
      mandatory: false
    - name: "irqbalance"
      mandatory: false
    - name: "systemd-zram-setup@zram0.service"
      mandatory: false
    - name: "docker"
      mandatory: false
    - name: "tlp"
      mandatory: false
    - name: "cups"
      mandatory: false
    - name: "avahi-daemon"
      mandatory: false
    - name: "fwupd-refresh.timer"
      mandatory: false
    - name: "systemd-timesyncd"
      mandatory: false
    - name: "pkgfile-update.timer"
      mandatory: false

targets:
    - name: "graphical"
      mandatory: true
