[global]
   workgroup = WORKGROUP
   server string = Sith OS
   security = user
   client min protocol = SMB2
   client max protocol = SMB3
   map to guest = Bad User
   usershare allow guests = yes

   # Performance
   socket options = TCP_NODELAY IPTOS_LOWDELAY
   use sendfile = yes

   # Disable printing (we use CUPS directly)
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes
