#? Config file for btop

color_theme = "sith_cyberpunk"
theme_background = false
vim_keys = true
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1500
proc_sorting = "cpu lazy"
proc_tree = false
proc_colors = true
proc_gradient = true
proc_per_core = false
cpu_graph_upper = "total"
cpu_graph_lower = "total"
show_gpu_info = "On"
